# Generated by Django 3.1.7 on 2021-02-22 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bug_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='description',
            field=models.TextField(),
        ),
    ]
